### PR TITLE
Add tolerance to all but grid alignment

### PR DESCRIPTION
**Pull request by Torsten-Mumme**

### CODE REVIEW

**Comment by Torsten-Mumme** [comment]
How about just merging and filing a bug for the special issue?

**Comment by Torsten-Mumme** [comment]
The "not" methods need the tolerance in the other direction. If overlap is more tolerant, just inverting it makes notOverlap less tolerant. As said - please merge and release a beta. Fix is going to follow.

**Comment by dzaiats** [comment]
@Torsten-Mumme , release in progress. Will be finished soon.

**Comment by Torsten-Mumme** [comment]
pushed a fix. but need to review all the not methods tomorrow. thank you!

**Pull request merged**
